name: podcast_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  google_sign_in: ^5.0.5
  flutter_facebook_login: ^3.0.0
  fluttertoast: ^8.0.8
  firebase_core: ^1.4.0
  cloud_firestore: ^2.4.0
  firebase_auth: ^3.0.1
  provider: ^5.0.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  get: ^4.3.0
  flutter_native_splash: ^1.2.0
  shared_preferences: ^2.0.6
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_native_splash:
  color: "#2D2C3C"
  image: assets/images/splash_screen.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFill

flutter_icons:
  image_path: "assets/images/podcast-icon.png"
  android: true
  ios: true



flutter:

  uses-material-design: true

  assets:
   - assets/images/
  fonts:
    - family: circular
      fonts:
        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 800
        - asset: assets/fonts/CircularStd-Book.ttf
          weight: 400
        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 600